/**
 * IabTaxonomy.gs
 *
 * IAB Content Taxonomy 1.0 - the code list reproduced by the Kayzen help article
 * (https://help.kayzen.io/en/articles/9104800-list-of-iab-categories).
 *
 * Generated from the IAB Tech Lab source of truth:
 *   https://github.com/InteractiveAdvertisingBureau/Taxonomies
 *   -> "Content Taxonomies/Content Taxonomy 1.0.tsv"
 *
 * Embedded rather than scraped at runtime: the list is a frozen standard, and the
 * Kayzen page is an Intercom article whose markup can change without notice.
 *
 * Rows are [code, name, tier1ParentName]. 392 entries (26 Tier 1, 366 Tier 2).
 *
 * NOTE: one upstream fix applied - IAB5-1 ships in the official TSV as
 * "41832 Education", an Excel date-mangling of "7-12 Education". Corrected here.
 */

var IAB_TAXONOMY = [
  ["IAB1", "Arts & Entertainment", ""],
  ["IAB1-1", "Books & Literature", "Arts & Entertainment"],
  ["IAB1-2", "Celebrity Fan/Gossip", "Arts & Entertainment"],
  ["IAB1-3", "Fine Art", "Arts & Entertainment"],
  ["IAB1-4", "Humor", "Arts & Entertainment"],
  ["IAB1-5", "Movies", "Arts & Entertainment"],
  ["IAB1-6", "Music", "Arts & Entertainment"],
  ["IAB1-7", "Television", "Arts & Entertainment"],
  ["IAB2", "Automotive", ""],
  ["IAB2-1", "Auto Parts", "Automotive"],
  ["IAB2-2", "Auto Repair", "Automotive"],
  ["IAB2-3", "Buying/Selling Cars", "Automotive"],
  ["IAB2-4", "Car Culture", "Automotive"],
  ["IAB2-5", "Certified Pre-Owned", "Automotive"],
  ["IAB2-6", "Convertible", "Automotive"],
  ["IAB2-7", "Coupe", "Automotive"],
  ["IAB2-8", "Crossover", "Automotive"],
  ["IAB2-9", "Diesel", "Automotive"],
  ["IAB2-10", "Electric Vehicle", "Automotive"],
  ["IAB2-11", "Hatchback", "Automotive"],
  ["IAB2-12", "Hybrid", "Automotive"],
  ["IAB2-13", "Luxury", "Automotive"],
  ["IAB2-14", "MiniVan", "Automotive"],
  ["IAB2-15", "Mororcycles", "Automotive"],
  ["IAB2-16", "Off-Road Vehicles", "Automotive"],
  ["IAB2-17", "Performance Vehicles", "Automotive"],
  ["IAB2-18", "Pickup", "Automotive"],
  ["IAB2-19", "Road-Side Assistance", "Automotive"],
  ["IAB2-20", "Sedan", "Automotive"],
  ["IAB2-21", "Trucks & Accessories", "Automotive"],
  ["IAB2-22", "Vintage Cars", "Automotive"],
  ["IAB2-23", "Wagon", "Automotive"],
  ["IAB3", "Business", ""],
  ["IAB3-1", "Advertising", "Business"],
  ["IAB3-2", "Agriculture", "Business"],
  ["IAB3-3", "Biotech/Biomedical", "Business"],
  ["IAB3-4", "Business Software", "Business"],
  ["IAB3-5", "Construction", "Business"],
  ["IAB3-6", "Forestry", "Business"],
  ["IAB3-7", "Government", "Business"],
  ["IAB3-8", "Green Solutions", "Business"],
  ["IAB3-9", "Human Resources", "Business"],
  ["IAB3-10", "Logistics", "Business"],
  ["IAB3-11", "Marketing", "Business"],
  ["IAB3-12", "Metals", "Business"],
  ["IAB4", "Careers", ""],
  ["IAB4-1", "Career Planning", "Careers"],
  ["IAB4-2", "College", "Careers"],
  ["IAB4-3", "Financial Aid", "Careers"],
  ["IAB4-4", "Job Fairs", "Careers"],
  ["IAB4-5", "Job Search", "Careers"],
  ["IAB4-6", "Resume Writing/Advice", "Careers"],
  ["IAB4-7", "Nursing", "Careers"],
  ["IAB4-8", "Scholarships", "Careers"],
  ["IAB4-9", "Telecommuting", "Careers"],
  ["IAB4-10", "U.S. Military", "Careers"],
  ["IAB4-11", "Career Advice", "Careers"],
  ["IAB5", "Education", ""],
  ["IAB5-1", "7-12 Education", "Education"],
  ["IAB5-2", "Adult Education", "Education"],
  ["IAB5-3", "Art History", "Education"],
  ["IAB5-4", "Colledge Administration", "Education"],
  ["IAB5-5", "College Life", "Education"],
  ["IAB5-6", "Distance Learning", "Education"],
  ["IAB5-7", "English as a 2nd Language", "Education"],
  ["IAB5-8", "Language Learning", "Education"],
  ["IAB5-9", "Graduate School", "Education"],
  ["IAB5-10", "Homeschooling", "Education"],
  ["IAB5-11", "Homework/Study Tips", "Education"],
  ["IAB5-12", "K-6 Educators", "Education"],
  ["IAB5-13", "Private School", "Education"],
  ["IAB5-14", "Special Education", "Education"],
  ["IAB5-15", "Studying Business", "Education"],
  ["IAB6", "Family & Parenting", ""],
  ["IAB6-1", "Adoption", "Family & Parenting"],
  ["IAB6-2", "Babies & Toddlers", "Family & Parenting"],
  ["IAB6-3", "Daycare/Pre School", "Family & Parenting"],
  ["IAB6-4", "Family Internet", "Family & Parenting"],
  ["IAB6-5", "Parenting - K-6 Kids", "Family & Parenting"],
  ["IAB6-6", "Parenting teens", "Family & Parenting"],
  ["IAB6-7", "Pregnancy", "Family & Parenting"],
  ["IAB6-8", "Special Needs Kids", "Family & Parenting"],
  ["IAB6-9", "Eldercare", "Family & Parenting"],
  ["IAB7", "Health & Fitness", ""],
  ["IAB7-1", "Exercise", "Health & Fitness"],
  ["IAB7-2", "A.D.D.", "Health & Fitness"],
  ["IAB7-3", "AIDS/HIV", "Health & Fitness"],
  ["IAB7-4", "Allergies", "Health & Fitness"],
  ["IAB7-5", "Alternative Medicine", "Health & Fitness"],
  ["IAB7-6", "Arthritis", "Health & Fitness"],
  ["IAB7-7", "Asthma", "Health & Fitness"],
  ["IAB7-8", "Autism/PDD", "Health & Fitness"],
  ["IAB7-9", "Bipolar Disorder", "Health & Fitness"],
  ["IAB7-10", "Brain Tumor", "Health & Fitness"],
  ["IAB7-11", "Cancer", "Health & Fitness"],
  ["IAB7-12", "Cholesterol", "Health & Fitness"],
  ["IAB7-13", "Chronic Fatigue Syndrome", "Health & Fitness"],
  ["IAB7-14", "Chronic Pain", "Health & Fitness"],
  ["IAB7-15", "Cold & Flu", "Health & Fitness"],
  ["IAB7-16", "Deafness", "Health & Fitness"],
  ["IAB7-17", "Dental Care", "Health & Fitness"],
  ["IAB7-18", "Depression", "Health & Fitness"],
  ["IAB7-19", "Dermatology", "Health & Fitness"],
  ["IAB7-20", "Diabetes", "Health & Fitness"],
  ["IAB7-21", "Epilepsy", "Health & Fitness"],
  ["IAB7-22", "GERD/Acid Reflux", "Health & Fitness"],
  ["IAB7-23", "Headaches/Migraines", "Health & Fitness"],
  ["IAB7-24", "Heart Disease", "Health & Fitness"],
  ["IAB7-25", "Herbs for Health", "Health & Fitness"],
  ["IAB7-26", "Holistic Healing", "Health & Fitness"],
  ["IAB7-27", "IBS/Crohn's Disease", "Health & Fitness"],
  ["IAB7-28", "Incest/Abuse Support", "Health & Fitness"],
  ["IAB7-29", "Incontinence", "Health & Fitness"],
  ["IAB7-30", "Infertility", "Health & Fitness"],
  ["IAB7-31", "Men's Health", "Health & Fitness"],
  ["IAB7-32", "Nutrition", "Health & Fitness"],
  ["IAB7-33", "Orthopedics", "Health & Fitness"],
  ["IAB7-34", "Panic/Anxiety Disorders", "Health & Fitness"],
  ["IAB7-35", "Pediatrics", "Health & Fitness"],
  ["IAB7-36", "Physical Therapy", "Health & Fitness"],
  ["IAB7-37", "Psychology/Psychiatry", "Health & Fitness"],
  ["IAB7-38", "Senor Health", "Health & Fitness"],
  ["IAB7-39", "Sexuality", "Health & Fitness"],
  ["IAB7-40", "Sleep Disorders", "Health & Fitness"],
  ["IAB7-41", "Smoking Cessation", "Health & Fitness"],
  ["IAB7-42", "Substance Abuse", "Health & Fitness"],
  ["IAB7-43", "Thyroid Disease", "Health & Fitness"],
  ["IAB7-44", "Weight Loss", "Health & Fitness"],
  ["IAB7-45", "Women's Health", "Health & Fitness"],
  ["IAB8", "Food & Drink", ""],
  ["IAB8-1", "American Cuisine", "Food & Drink"],
  ["IAB8-2", "Barbecues & Grilling", "Food & Drink"],
  ["IAB8-3", "Cajun/Creole", "Food & Drink"],
  ["IAB8-4", "Chinese Cuisine", "Food & Drink"],
  ["IAB8-5", "Cocktails/Beer", "Food & Drink"],
  ["IAB8-6", "Coffee/Tea", "Food & Drink"],
  ["IAB8-7", "Cuisine-Specific", "Food & Drink"],
  ["IAB8-8", "Desserts & Baking", "Food & Drink"],
  ["IAB8-9", "Dining Out", "Food & Drink"],
  ["IAB8-10", "Food Allergies", "Food & Drink"],
  ["IAB8-11", "French Cuisine", "Food & Drink"],
  ["IAB8-12", "Health/Lowfat Cooking", "Food & Drink"],
  ["IAB8-13", "Italian Cuisine", "Food & Drink"],
  ["IAB8-14", "Japanese Cuisine", "Food & Drink"],
  ["IAB8-15", "Mexican Cuisine", "Food & Drink"],
  ["IAB8-16", "Vegan", "Food & Drink"],
  ["IAB8-17", "Vegetarian", "Food & Drink"],
  ["IAB8-18", "Wine", "Food & Drink"],
  ["IAB9", "Hobbies & Interests", ""],
  ["IAB9-1", "Art/Technology", "Hobbies & Interests"],
  ["IAB9-2", "Arts & Crafts", "Hobbies & Interests"],
  ["IAB9-3", "Beadwork", "Hobbies & Interests"],
  ["IAB9-4", "Birdwatching", "Hobbies & Interests"],
  ["IAB9-5", "Board Games/Puzzles", "Hobbies & Interests"],
  ["IAB9-6", "Candle & Soap Making", "Hobbies & Interests"],
  ["IAB9-7", "Card Games", "Hobbies & Interests"],
  ["IAB9-8", "Chess", "Hobbies & Interests"],
  ["IAB9-9", "Cigars", "Hobbies & Interests"],
  ["IAB9-10", "Collecting", "Hobbies & Interests"],
  ["IAB9-11", "Comic Books", "Hobbies & Interests"],
  ["IAB9-12", "Drawing/Sketching", "Hobbies & Interests"],
  ["IAB9-13", "Freelance Writing", "Hobbies & Interests"],
  ["IAB9-14", "Genealogy", "Hobbies & Interests"],
  ["IAB9-15", "Getting Published", "Hobbies & Interests"],
  ["IAB9-16", "Guitar", "Hobbies & Interests"],
  ["IAB9-17", "Home Recording", "Hobbies & Interests"],
  ["IAB9-18", "Investors & Patents", "Hobbies & Interests"],
  ["IAB9-19", "Jewelry Making", "Hobbies & Interests"],
  ["IAB9-20", "Magic & Illusion", "Hobbies & Interests"],
  ["IAB9-21", "Needlework", "Hobbies & Interests"],
  ["IAB9-22", "Painting", "Hobbies & Interests"],
  ["IAB9-23", "Photography", "Hobbies & Interests"],
  ["IAB9-24", "Radio", "Hobbies & Interests"],
  ["IAB9-25", "Roleplaying Games", "Hobbies & Interests"],
  ["IAB9-26", "Sci-Fi & Fantasy", "Hobbies & Interests"],
  ["IAB9-27", "Scrapbooking", "Hobbies & Interests"],
  ["IAB9-28", "Screenwriting", "Hobbies & Interests"],
  ["IAB9-29", "Stamps & Coins", "Hobbies & Interests"],
  ["IAB9-30", "Video & Computer Games", "Hobbies & Interests"],
  ["IAB9-31", "Woodworking", "Hobbies & Interests"],
  ["IAB10", "Home & Garden", ""],
  ["IAB10-1", "Appliances", "Home & Garden"],
  ["IAB10-2", "Entertaining", "Home & Garden"],
  ["IAB10-3", "Environmental Safety", "Home & Garden"],
  ["IAB10-4", "Gardening", "Home & Garden"],
  ["IAB10-5", "Home Repair", "Home & Garden"],
  ["IAB10-6", "Home Theater", "Home & Garden"],
  ["IAB10-7", "Interior Decorating", "Home & Garden"],
  ["IAB10-8", "Landscaping", "Home & Garden"],
  ["IAB10-9", "Remodeling & Construction", "Home & Garden"],
  ["IAB11", "Law, Gov't & Politics", ""],
  ["IAB11-1", "Immigration", "Law, Gov't & Politics"],
  ["IAB11-2", "Legal Issues", "Law, Gov't & Politics"],
  ["IAB11-3", "U.S. Government Resources", "Law, Gov't & Politics"],
  ["IAB11-4", "Politics", "Law, Gov't & Politics"],
  ["IAB11-5", "Commentary", "Law, Gov't & Politics"],
  ["IAB12", "News", ""],
  ["IAB12-1", "International News", "News"],
  ["IAB12-2", "National News", "News"],
  ["IAB12-3", "Local News", "News"],
  ["IAB13", "Personal Finance", ""],
  ["IAB13-1", "Beginning Investing", "Personal Finance"],
  ["IAB13-2", "Credit/Debt & Loans", "Personal Finance"],
  ["IAB13-3", "Financial News", "Personal Finance"],
  ["IAB13-4", "Financial Planning", "Personal Finance"],
  ["IAB13-5", "Hedge Fund", "Personal Finance"],
  ["IAB13-6", "Insurance", "Personal Finance"],
  ["IAB13-7", "Investing", "Personal Finance"],
  ["IAB13-8", "Mutual Funds", "Personal Finance"],
  ["IAB13-9", "Options", "Personal Finance"],
  ["IAB13-10", "Retirement Planning", "Personal Finance"],
  ["IAB13-11", "Stocks", "Personal Finance"],
  ["IAB13-12", "Tax Planning", "Personal Finance"],
  ["IAB14", "Society", ""],
  ["IAB14-1", "Dating", "Society"],
  ["IAB14-2", "Divorce Support", "Society"],
  ["IAB14-3", "Gay Life", "Society"],
  ["IAB14-4", "Marriage", "Society"],
  ["IAB14-5", "Senior Living", "Society"],
  ["IAB14-6", "Teens", "Society"],
  ["IAB14-7", "Weddings", "Society"],
  ["IAB14-8", "Ethnic Specific", "Society"],
  ["IAB15", "Science", ""],
  ["IAB15-1", "Astrology", "Science"],
  ["IAB15-2", "Biology", "Science"],
  ["IAB15-3", "Chemistry", "Science"],
  ["IAB15-4", "Geology", "Science"],
  ["IAB15-5", "Paranormal Phenomena", "Science"],
  ["IAB15-6", "Physics", "Science"],
  ["IAB15-7", "Space/Astronomy", "Science"],
  ["IAB15-8", "Geography", "Science"],
  ["IAB15-9", "Botany", "Science"],
  ["IAB15-10", "Weather", "Science"],
  ["IAB16", "Pets", ""],
  ["IAB16-1", "Aquariums", "Pets"],
  ["IAB16-2", "Birds", "Pets"],
  ["IAB16-3", "Cats", "Pets"],
  ["IAB16-4", "Dogs", "Pets"],
  ["IAB16-5", "Large Animals", "Pets"],
  ["IAB16-6", "Reptiles", "Pets"],
  ["IAB16-7", "Veterinary Medicine", "Pets"],
  ["IAB17", "Sports", ""],
  ["IAB17-1", "Auto Racing", "Sports"],
  ["IAB17-2", "Baseball", "Sports"],
  ["IAB17-3", "Bicycling", "Sports"],
  ["IAB17-4", "Bodybuilding", "Sports"],
  ["IAB17-5", "Boxing", "Sports"],
  ["IAB17-6", "Canoeing/Kayaking", "Sports"],
  ["IAB17-7", "Cheerleading", "Sports"],
  ["IAB17-8", "Climbing", "Sports"],
  ["IAB17-9", "Cricket", "Sports"],
  ["IAB17-10", "Figure Skating", "Sports"],
  ["IAB17-11", "Fly Fishing", "Sports"],
  ["IAB17-12", "Football", "Sports"],
  ["IAB17-13", "Freshwater Fishing", "Sports"],
  ["IAB17-14", "Game & Fish", "Sports"],
  ["IAB17-15", "Golf", "Sports"],
  ["IAB17-16", "Horse Racing", "Sports"],
  ["IAB17-17", "Horses", "Sports"],
  ["IAB17-18", "Hunting/Shooting", "Sports"],
  ["IAB17-19", "Inline Skating", "Sports"],
  ["IAB17-20", "Martial Arts", "Sports"],
  ["IAB17-21", "Mountain Biking", "Sports"],
  ["IAB17-22", "NASCAR Racing", "Sports"],
  ["IAB17-23", "Olympics", "Sports"],
  ["IAB17-24", "Paintball", "Sports"],
  ["IAB17-25", "Power & Motorcycles", "Sports"],
  ["IAB17-26", "Pro Basketball", "Sports"],
  ["IAB17-27", "Pro Ice Hockey", "Sports"],
  ["IAB17-28", "Rodeo", "Sports"],
  ["IAB17-29", "Rugby", "Sports"],
  ["IAB17-30", "Running/Jogging", "Sports"],
  ["IAB17-31", "Sailing", "Sports"],
  ["IAB17-32", "Saltwater Fishing", "Sports"],
  ["IAB17-33", "Scuba Diving", "Sports"],
  ["IAB17-34", "Skateboarding", "Sports"],
  ["IAB17-35", "Skiing", "Sports"],
  ["IAB17-36", "Snowboarding", "Sports"],
  ["IAB17-37", "Surfing/Bodyboarding", "Sports"],
  ["IAB17-38", "Swimming", "Sports"],
  ["IAB17-39", "Table Tennis/Ping-Pong", "Sports"],
  ["IAB17-40", "Tennis", "Sports"],
  ["IAB17-41", "Volleyball", "Sports"],
  ["IAB17-42", "Walking", "Sports"],
  ["IAB17-43", "Waterski/Wakeboard", "Sports"],
  ["IAB17-44", "World Soccer", "Sports"],
  ["IAB18", "Style & Fashion", ""],
  ["IAB18-1", "Beauty", "Style & Fashion"],
  ["IAB18-2", "Body Art", "Style & Fashion"],
  ["IAB18-3", "Fashion", "Style & Fashion"],
  ["IAB18-4", "Jewelry", "Style & Fashion"],
  ["IAB18-5", "Clothing", "Style & Fashion"],
  ["IAB18-6", "Accessories", "Style & Fashion"],
  ["IAB19", "Technology & Computing", ""],
  ["IAB19-1", "3-D Graphics", "Technology & Computing"],
  ["IAB19-2", "Animation", "Technology & Computing"],
  ["IAB19-3", "Antivirus Software", "Technology & Computing"],
  ["IAB19-4", "C/C++", "Technology & Computing"],
  ["IAB19-5", "Cameras & Camcorders", "Technology & Computing"],
  ["IAB19-6", "Cell Phones", "Technology & Computing"],
  ["IAB19-7", "Computer Certification", "Technology & Computing"],
  ["IAB19-8", "Computer Networking", "Technology & Computing"],
  ["IAB19-9", "Computer Peripherals", "Technology & Computing"],
  ["IAB19-10", "Computer Reviews", "Technology & Computing"],
  ["IAB19-11", "Data Centers", "Technology & Computing"],
  ["IAB19-12", "Databases", "Technology & Computing"],
  ["IAB19-13", "Desktop Publishing", "Technology & Computing"],
  ["IAB19-14", "Desktop Video", "Technology & Computing"],
  ["IAB19-15", "Email", "Technology & Computing"],
  ["IAB19-16", "Graphics Software", "Technology & Computing"],
  ["IAB19-17", "Home Video/DVD", "Technology & Computing"],
  ["IAB19-18", "Internet Technology", "Technology & Computing"],
  ["IAB19-19", "Java", "Technology & Computing"],
  ["IAB19-20", "JavaScript", "Technology & Computing"],
  ["IAB19-21", "Mac Support", "Technology & Computing"],
  ["IAB19-22", "MP3/MIDI", "Technology & Computing"],
  ["IAB19-23", "Net Conferencing", "Technology & Computing"],
  ["IAB19-24", "Net for Beginners", "Technology & Computing"],
  ["IAB19-25", "Network Security", "Technology & Computing"],
  ["IAB19-26", "Palmtops/PDAs", "Technology & Computing"],
  ["IAB19-27", "PC Support", "Technology & Computing"],
  ["IAB19-28", "Portable", "Technology & Computing"],
  ["IAB19-29", "Entertainment", "Technology & Computing"],
  ["IAB19-30", "Shareware/Freeware", "Technology & Computing"],
  ["IAB19-31", "Unix", "Technology & Computing"],
  ["IAB19-32", "Visual Basic", "Technology & Computing"],
  ["IAB19-33", "Web Clip Art", "Technology & Computing"],
  ["IAB19-34", "Web Design/HTML", "Technology & Computing"],
  ["IAB19-35", "Web Search", "Technology & Computing"],
  ["IAB19-36", "Windows", "Technology & Computing"],
  ["IAB20", "Travel", ""],
  ["IAB20-1", "Adventure Travel", "Travel"],
  ["IAB20-2", "Africa", "Travel"],
  ["IAB20-3", "Air Travel", "Travel"],
  ["IAB20-4", "Australia & New Zealand", "Travel"],
  ["IAB20-5", "Bed & Breakfasts", "Travel"],
  ["IAB20-6", "Budget Travel", "Travel"],
  ["IAB20-7", "Business Travel", "Travel"],
  ["IAB20-8", "By US Locale", "Travel"],
  ["IAB20-9", "Camping", "Travel"],
  ["IAB20-10", "Canada", "Travel"],
  ["IAB20-11", "Caribbean", "Travel"],
  ["IAB20-12", "Cruises", "Travel"],
  ["IAB20-13", "Eastern Europe", "Travel"],
  ["IAB20-14", "Europe", "Travel"],
  ["IAB20-15", "France", "Travel"],
  ["IAB20-16", "Greece", "Travel"],
  ["IAB20-17", "Honeymoons/Getaways", "Travel"],
  ["IAB20-18", "Hotels", "Travel"],
  ["IAB20-19", "Italy", "Travel"],
  ["IAB20-20", "Japan", "Travel"],
  ["IAB20-21", "Mexico & Central America", "Travel"],
  ["IAB20-22", "National Parks", "Travel"],
  ["IAB20-23", "South America", "Travel"],
  ["IAB20-24", "Spas", "Travel"],
  ["IAB20-25", "Theme Parks", "Travel"],
  ["IAB20-26", "Traveling with Kids", "Travel"],
  ["IAB20-27", "United Kingdom", "Travel"],
  ["IAB21", "Real Estate", ""],
  ["IAB21-1", "Apartments", "Real Estate"],
  ["IAB21-2", "Architects", "Real Estate"],
  ["IAB21-3", "Buying/Selling Homes", "Real Estate"],
  ["IAB22", "Shopping", ""],
  ["IAB22-1", "Contests & Freebies", "Shopping"],
  ["IAB22-2", "Couponing", "Shopping"],
  ["IAB22-3", "Comparison", "Shopping"],
  ["IAB22-4", "Engines", "Shopping"],
  ["IAB23", "Religion & Spirituality", ""],
  ["IAB23-1", "Alternative Religions", "Religion & Spirituality"],
  ["IAB23-2", "Atheism/Agnosticism", "Religion & Spirituality"],
  ["IAB23-3", "Buddhism", "Religion & Spirituality"],
  ["IAB23-4", "Catholicism", "Religion & Spirituality"],
  ["IAB23-5", "Christianity", "Religion & Spirituality"],
  ["IAB23-6", "Hinduism", "Religion & Spirituality"],
  ["IAB23-7", "Islam", "Religion & Spirituality"],
  ["IAB23-8", "Judaism", "Religion & Spirituality"],
  ["IAB23-9", "Latter-Day Saints", "Religion & Spirituality"],
  ["IAB23-10", "Pagan/Wiccan", "Religion & Spirituality"],
  ["IAB24", "Uncategorized", ""],
  ["IAB25", "Non-Standard Content", ""],
  ["IAB25-1", "Unmoderated UGC", "Non-Standard Content"],
  ["IAB25-2", "Extreme Graphic/Explicit Violence", "Non-Standard Content"],
  ["IAB25-3", "Pornography", "Non-Standard Content"],
  ["IAB25-4", "Profane Content", "Non-Standard Content"],
  ["IAB25-5", "Hate Content", "Non-Standard Content"],
  ["IAB25-6", "Under Construction", "Non-Standard Content"],
  ["IAB25-7", "Incentivized", "Non-Standard Content"],
  ["IAB26", "Illegal Content", ""],
  ["IAB26-1", "Illegal Content", "Illegal Content"],
  ["IAB26-2", "Warez", "Illegal Content"],
  ["IAB26-3", "Spyware/Malware", "Illegal Content"],
  ["IAB26-4", "Copyright Infringement", "Illegal Content"]
];
